services:
  - type: web
    name: waya-backend-service
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn waya_backend.wsgi:application
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: waya-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: ENVIRONMENT
        value: production
      - key: SENDGRID_API_KEY
        sync: false
      - key: DEFAULT_FROM_EMAIL
        sync: false
      - key: GOOGLE_CLIENT_ID
        sync: false
      - key: GOOGLE_CLIENT_SECRET
        sync: false
      - key: domain
        value: https://waya-backend-service.onrender.com
      - key: ALLOWED_HOSTS
        value: waya-backend-service.onrender.com

databases:
  - name: waya-db
    plan: free
