# Generated by Django 5.2 on 2025-06-26 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskmaster', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='category',
            field=models.CharField(default='Household', max_length=50),
        ),
    ]
