# Generated by Django 5.2 on 2025-06-17 10:03

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('children', '0001_initial'),
        ('taskmaster', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChildWallet',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text="Child's personal wallet balance", max_digits=10)),
                ('total_earned', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total amount earned by child', max_digits=10)),
                ('total_spent', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total amount spent by child', max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('child', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wallet', to='children.child')),
            ],
        ),
        migrations.CreateModel(
            name='FamilyWallet',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Main family wallet balance', max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent', models.OneToOneField(limit_choices_to={'role': 'parent'}, on_delete=django.db.models.deletion.CASCADE, related_name='family_wallet', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('transaction_type', models.CharField(choices=[('reward', 'Reward'), ('spending', 'Spending'), ('deposit', 'Deposit'), ('transfer', 'Transfer'), ('withdrawal', 'Withdrawal')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('child', models.ForeignKey(blank=True, help_text='Child involved in the transaction (for rewards/spending)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='children.child')),
                ('family_wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='familywallet.familywallet')),
                ('task', models.ForeignKey(blank=True, help_text='Task associated with reward transaction', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='taskmaster.task')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['transaction_type', 'status'], name='familywalle_transac_4a8c12_idx'), models.Index(fields=['child', 'created_at'], name='familywalle_child_i_0385f5_idx'), models.Index(fields=['family_wallet', 'created_at'], name='familywalle_family__755719_idx')],
            },
        ),
        migrations.CreateModel(
            name='TransactionCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('color', models.CharField(default='#000000', help_text='Hex color code', max_length=7)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('parent', models.ForeignKey(limit_choices_to={'role': 'parent'}, on_delete=django.db.models.deletion.CASCADE, related_name='transaction_categories', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Transaction Categories',
                'unique_together': {('name', 'parent')},
            },
        ),
    ]
