# Generated by Django 5.2 on 2025-07-11 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('familywallet', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='type',
            field=models.CharField(choices=[('chore_reward', 'Chore Reward'), ('allowance_payment', 'Allowance Payment'), ('wallet_funding', 'Wallet Funding')], default='chore_reward', max_length=20),
        ),
    ]
