# Generated by Django 5.2 on 2025-07-19 01:12

import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('children', '0004_child_children_ch_parent__6a03e7_idx_and_more'),
        ('familywallet', '0003_transaction_reference'),
        ('taskmaster', '0002_alter_chore_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transaction',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterField(
            model_name='allowance',
            name='amount',
            field=models.DecimalField(db_index=True, decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='allowance',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='allowance',
            name='frequency',
            field=models.CharField(choices=[('weekly', 'Weekly'), ('monthly', 'Monthly')], db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='allowance',
            name='id',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='allowance',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('paused', 'Paused'), ('pending', 'Pending')], db_index=True, default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='childwallet',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='familywallet',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AddIndex(
            model_name='allowance',
            index=models.Index(fields=['parent'], name='familywalle_parent__1615e9_idx'),
        ),
        migrations.AddIndex(
            model_name='allowance',
            index=models.Index(fields=['child'], name='familywalle_child_i_237118_idx'),
        ),
        migrations.AddIndex(
            model_name='allowance',
            index=models.Index(fields=['status'], name='familywalle_status_30841d_idx'),
        ),
        migrations.AddIndex(
            model_name='allowance',
            index=models.Index(fields=['frequency'], name='familywalle_frequen_6c0222_idx'),
        ),
        migrations.AddIndex(
            model_name='allowance',
            index=models.Index(fields=['created_at'], name='familywalle_created_5269a1_idx'),
        ),
        migrations.AddIndex(
            model_name='allowance',
            index=models.Index(fields=['parent', 'child'], name='familywalle_parent__7260af_idx'),
        ),
        migrations.AddIndex(
            model_name='familywallet',
            index=models.Index(fields=['parent'], name='familywalle_parent__addc57_idx'),
        ),
        migrations.AddIndex(
            model_name='familywallet',
            index=models.Index(fields=['created_at'], name='familywalle_created_a65f3a_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['parent'], name='familywalle_parent__c4678c_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['child'], name='familywalle_child_i_98035b_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['status'], name='familywalle_status_95878a_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['type'], name='familywalle_type_f7dc2e_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['created_at'], name='familywalle_created_052aeb_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['parent', 'child'], name='familywalle_parent__52b4cc_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['status', 'created_at'], name='familywalle_status_2d07a7_idx'),
        ),
    ]
