# Generated by Django 5.2 on 2025-07-15 02:00

import django.db.models.deletion
import moneymaze.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('children', '0001_initial'),
        ('moneymaze', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConceptSection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('order', models.PositiveIntegerField(default=1)),
                ('concept', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='moneymaze.concept')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='SectionProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('viewed', models.BooleanField(default=False)),
                ('viewed_on', models.DateTimeField(auto_now_add=True)),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='section_progress', to='children.child')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='viewed_by', to='moneymaze.conceptsection')),
            ],
            options={
                'unique_together': {('child', 'section')},
            },
        ),
        migrations.CreateModel(
            name='WeeklyStreak',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_start_date', models.DateField()),
                ('streak', models.JSONField(default=moneymaze.models.default_streak)),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weekly_streaks', to='children.child')),
            ],
            options={
                'unique_together': {('child', 'week_start_date')},
            },
        ),
    ]
