# Generated by Django 5.2 on 2025-07-22 11:15

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moneymaze', '0002_conceptsection_sectionprogress_weeklystreak'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='concept',
            name='description',
        ),
        migrations.RemoveField(
            model_name='concept',
            name='order',
        ),
        migrations.CreateModel(
            name='ConceptDescription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('text', models.TextField()),
                ('order', models.PositiveIntegerField(default=1)),
                ('concept', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='descriptions', to='moneymaze.concept')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
