# Generated by Django 5.2 on 2025-07-22 12:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moneymaze', '0003_remove_concept_description_remove_concept_order_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conceptdescription',
            name='concept',
        ),
        migrations.RemoveField(
            model_name='conceptsection',
            name='content',
        ),
        migrations.AddField(
            model_name='conceptdescription',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='descriptions', to='moneymaze.conceptsection'),
        ),
    ]
