# Generated by Django 5.2 on 2025-07-22 13:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moneymaze', '0004_remove_conceptdescription_concept_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conceptdescription',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='descriptions', to='moneymaze.conceptsection'),
        ),
    ]
