# Generated by Django 5.2 on 2025-07-22 18:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moneymaze', '0006_alter_conceptdescription_section'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conceptdescription',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moneymaze.conceptsection'),
        ),
    ]
