# Generated by Django 5.2 on 2025-07-22 18:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moneymaze', '0007_alter_conceptdescription_section'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conceptdescription',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='descriptions', to='moneymaze.conceptsection'),
        ),
    ]
