# Generated by Django 5.2 on 2025-07-22 20:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moneymaze', '0008_alter_conceptdescription_section'),
    ]

    operations = [
        migrations.AddField(
            model_name='conceptsection',
            name='content',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='conceptdescription',
            name='section',
            field=models.ForeignKey(default='e778df4e-a1b5-4fe9-9cbc-372b4484d7d5', on_delete=django.db.models.deletion.CASCADE, related_name='descriptions', to='moneymaze.conceptsection'),
            preserve_default=False,
        ),
    ]
