# Generated by Django 5.2 on 2025-06-26 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('children', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='child',
            name='name',
            field=models.CharField(default='Unknown', max_length=255),
        ),
    ]
