# Generated by Django 5.2 on 2025-07-16 02:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('children', '0002_child_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='child',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='child',
            name='user',
        ),
    ]
