# Generated by Django 5.2 on 2025-07-18 23:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('children', '0003_alter_child_options_remove_child_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='child',
            index=models.Index(fields=['parent'], name='children_ch_parent__6a03e7_idx'),
        ),
        migrations.AddIndex(
            model_name='child',
            index=models.Index(fields=['username'], name='children_ch_usernam_716922_idx'),
        ),
    ]
