# Generated by Django 5.2 on 2025-07-04 22:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chore_completion', models.BooleanField(default=True)),
                ('reward_redemption', models.BooleanField(default=True)),
                ('chore_reminder', models.BooleanField(default=True)),
                ('weekly_summary', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_settings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RewardSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reward_approval_required', models.BooleanField(default=False)),
                ('max_daily_reward', models.PositiveIntegerField(default=0)),
                ('allow_savings', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='reward_settings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
